### ISSUE TITLE
Feature: User can receive a random Spanish word.

### ISSUE THREAD

**Issue by gavenlou** [gavenlou/ajax-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view a random Spanish word.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can continuously request new random words.

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Build a basic html page.
- [x] Add 'flashcard' box in screen along with unique ID.
- [x] Create an XML request to retrieve a random word from the API.
- [x] Parse the return, and change flashcard text content to the word.
- [x] Check for useless code/styles.
