### ISSUE TITLE
Feature: User can view the word in English

### ISSUE THREAD

**Issue by gavenlou** [gavenlou/ajax-project#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view the word in English after guessing incorrectly.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

After an incorrect guess the user can view the word in English as opposed to the current Spanish.

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add input box below flashcard for user input.
- [x] Make an XML request for the translated spanish word.
- [x] Check the user input against the returned English translation from the API.
- [x] Change box border/text color based on answer.
- [x] If incorrect offer to see the translation, or keep guessing.
- [x] Check for useless code/styles.
