### ISSUE TITLE
Feature: User can view a definition/picture of the word.

### ISSUE THREAD

**Issue by gavenlou** [gavenlou/ajax-project#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view the definition/image of the word received.
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can click on a button on the flashcard to see the image/definition(English) of the current Spanish word.

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create a 'View Definition' and 'View Image' Button.
- [ ] #8
- [ ] Parse the return and create the img tag when needed.
- [x] Swap from Word to the Definition/Image on click.
- [x] Swap back from Definition/Image to Word on click.
- [x] Remove useless code/styles.
