### ISSUE TITLE
Feature: User can view past words.

### ISSUE THREAD

**Issue by gavenlou** [gavenlou/ajax-project#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view a history of words they've completed.
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can click on a button to see a list of words they've completed.

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] Create a new 'tab' to swap to upon clicking a 'Past Words' button.
- [ ] Save each word/definition/image to local storage before getting a new word.
- [ ] Parse the local storage for past words and update the 'Past Words' Tab when opened.
- [ ] Remove excess code.
