### ISSUE TITLE
Feature: User can create their own word list

### ISSUE THREAD

**Issue by gavenlou** [gavenlou/ajax-project#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can 'add' certain words to their list to go over instead of using randomly generated ones.
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can click a button to view their current list of words and can add/remove them while there.
## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] Create a new 'Tab' for the 'My Words' Section.
- [ ] Create a modal which allows text input for new words.
- [ ] Allow user to add words from the past words list also.
- [ ] Allow user to remove words from their current list.
- [ ] Create a button on home screen to swap from random words to their list.
- [ ] Randomize the word list order.
- [ ] Remove excess code.
